#开发环境下的配置文件，覆盖application.yml中的配置
sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 12345
  redis:
    host: localhost
    port: 6379
    auth: 12345
    database: 10
  wechat:
    appid: wxd9ad8168b93ad6a7
    secret: 4dd77f121653ff5cebfebceadcbf275e
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: rich-tams
    #    //新版工具包从环境变量中获取访问凭证，因此无需配置这两项
    #    access-key-id:
    #    access-key-secret:
